#!/usr/bin/env python3
"""Extract the Cardputer's bitmap fonts for the Cardmic window.

    python3 make_fonts.py path/to/M5GFX/src/lgfx/Fonts > fonts.js

The window draws text with the same bitmaps the device does, so the two look
the same. Sources, all from M5GFX (MIT), each under its own license:
  - glcdfont.h: the classic 5x7 Adafruit GFX font ("Font0"), BSD license
  - Custom/DejaVu12.h: DejaVu Sans 12, Bitstream Vera / DejaVu license
  - Custom/Orbitron_Light_24.h: Orbitron Light by Matt McInerney, SIL OFL 1.1
"""
import base64
import json
import os
import re
import sys


def hex_bytes(text):
    return bytes(int(h, 16) for h in re.findall(r"0x([0-9A-Fa-f]{2})\b", text))


def glcd(path):
    src = open(path).read()
    body = src[src.index("font[] PROGMEM = {"):]
    body = body[: body.index("};")]
    data = hex_bytes(body)
    assert len(data) == 256 * 5, len(data)
    return {"w": 5, "cell": [6, 8], "data": base64.b64encode(data).decode()}


def gfx(path, name):
    src = open(path).read()
    bm = src[src.index(f"{name}Bitmaps[]"):]
    bm = bm[bm.index("{") + 1: bm.index("};")]
    # Drop comments first: they contain things like '0' and ','.
    bm = re.sub(r"//[^\n]*", "", bm)
    bitmap = hex_bytes(bm)
    gl = src[src.index(f"{name}Glyphs[]"):]
    gl = gl[gl.index("{") + 1: gl.index("};")]
    gl = re.sub(r"//[^\n]*", "", gl)
    glyphs = [list(map(int, g)) for g in re.findall(r"\{\s*(-?\d+),\s*(-?\d+),\s*(-?\d+),\s*(-?\d+),\s*(-?\d+),\s*(-?\d+)\s*\}", gl)]
    tail = src[src.index(f"GFXfont {name}"):]
    first, last, y_adv = re.findall(r"(0x[0-9A-Fa-f]+|\d+)\s*,\s*(0x[0-9A-Fa-f]+|\d+)\s*,\s*(\d+)\s*\}", tail)[0]
    first, last = int(first, 0), int(last, 0)
    assert len(glyphs) == last - first + 1, (name, len(glyphs), first, last)
    return {"first": first, "yAdvance": int(y_adv), "bitmap": base64.b64encode(bitmap).decode(), "glyphs": glyphs}


def main():
    fonts = sys.argv[1] if len(sys.argv) > 1 else "."
    out = {
        "font0": glcd(os.path.join(fonts, "glcdfont.h")),
        "dejavu12": gfx(os.path.join(fonts, "Custom/DejaVu12.h"), "DejaVu12"),
        "orbitron24": gfx(os.path.join(fonts, "Custom/Orbitron_Light_24.h"), "Orbitron_Light_24"),
    }
    print("// Generated by make_fonts.py from M5GFX; see that script for sources and licenses.")
    print("window.CARDMIC_FONTS = " + json.dumps(out, separators=(",", ":")) + ";")


if __name__ == "__main__":
    main()
