#!/usr/bin/env python3
"""Extract the Cardputer's bitmap fonts for the Cardmic window.

    python3 make_fonts.py path/to/M5GFX/src/lgfx/Fonts > fonts.js

The window's dot-matrix lettering uses the device's own 5x7 font, from
M5GFX (MIT): glcdfont.h, the classic Adafruit GFX font ("Font0"), BSD license.
"""
import base64
import json
import os
import re
import sys


def hex_bytes(text):
    return bytes(int(h, 16) for h in re.findall(r"0x([0-9A-Fa-f]{2})\b", text))


def glcd(path):
    src = open(path).read()
    body = src[src.index("font[] PROGMEM = {"):]
    body = body[: body.index("};")]
    data = hex_bytes(body)
    assert len(data) == 256 * 5, len(data)
    return {"w": 5, "cell": [6, 8], "data": base64.b64encode(data).decode()}


def main():
    fonts = sys.argv[1] if len(sys.argv) > 1 else "."
    out = {"font0": glcd(os.path.join(fonts, "glcdfont.h"))}
    print("// Generated by make_fonts.py from M5GFX; see that script for sources and licenses.")
    print("window.CARDMIC_FONTS = " + json.dumps(out, separators=(",", ":")) + ";")


if __name__ == "__main__":
    main()
