#!/usr/bin/env python3
"""Generate the Cardmic launcher icons (56x56 and 40x40) as RGB565 C arrays.

The stock launcher draws each icon on a light-grey (#E6E6E6) rounded tile and
expects byte-swapped RGB565, which is what lcd-image-converter emitted for the
stock icons. The design echoes the app itself: a black "screen" holding seven
mirrored bars in the Cardmic heat palette.

Usage: python3 tools/make_cardmic_icon.py [--png-dir DIR]
"""
import argparse
import os
from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "main", "apps", "app_cardmic", "assets")
TILE = (0xE6, 0xE6, 0xE6)
HEAT = [(0.00, (0x1B, 0x2A, 0x6B)), (0.22, (0x2F, 0x6B, 0xFF)), (0.42, (0x28, 0xF0, 0xFF)),
        (0.62, (0x99, 0xFF, 0x00)), (0.80, (0xFF, 0xD0, 0x00)), (1.00, (0xFF, 0x3B, 0x3B))]
BARS = [0.34, 0.62, 0.92, 0.55, 1.00, 0.70, 0.40]  # half-heights, fraction of max


def heat(t):
    t = max(0.0, min(1.0, t))
    for (a, ca), (b, cb) in zip(HEAT, HEAT[1:]):
        if t <= b:
            u = (t - a) / (b - a)
            return tuple(round(x + (y - x) * u) for x, y in zip(ca, cb))
    return HEAT[-1][1]


def render(size, scale=8):
    s = size * scale
    img = Image.new("RGB", (s, s), TILE)
    d = ImageDraw.Draw(img)
    inset, radius = round(s * 0.04), round(s * 0.14)
    d.rounded_rectangle([inset, inset, s - 1 - inset, s - 1 - inset], radius=radius, fill=(0, 0, 0))
    n, cx0, cx1 = len(BARS), s * 0.19, s * 0.81
    pitch = (cx1 - cx0) / (n - 1)
    bw = pitch * 0.58
    cy, max_half = s / 2, s * 0.30
    for i, h in enumerate(BARS):
        x = cx0 + i * pitch
        half = max_half * h
        # vertical heat gradient from the centre line outwards, like the app
        steps = max(1, int(half))
        for k in range(steps):
            col = heat(k / max_half)
            d.rectangle([x - bw / 2, cy - k - 1, x + bw / 2, cy - k], fill=col)
            d.rectangle([x - bw / 2, cy + k, x + bw / 2, cy + k + 1], fill=col)
        # round the tips
        r = bw / 2
        d.ellipse([x - r, cy - half - r, x + r, cy - half + r], fill=heat(half / max_half))
        d.ellipse([x - r, cy + half - r, x + r, cy + half + r], fill=heat(half / max_half))
    return img.resize((size, size), Image.LANCZOS)


def to_header(img, name):
    w, h = img.size
    words = []
    for r, g, b in img.getdata():
        c = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        words.append(((c & 0xFF) << 8) | (c >> 8))  # byte-swapped, as the stock icons
    lines = [", ".join(f"0x{v:04x}" for v in words[i:i + w]) for i in range(0, len(words), w)]
    body = ",\n    ".join(lines)
    return (f"// Generated by tools/make_cardmic_icon.py -- do not edit.\n"
            f"// {w}x{h}, byte-swapped RGB565, drawn on the stock #E6E6E6 icon tile.\n"
            f"#pragma once\n#include <stdint.h>\n\n"
            f"static const uint16_t {name}[{w * h}] = {{\n    {body}\n}};\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--png-dir")
    args = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)
    for size, name in ((56, "image_data_cardmic_big"), (40, "image_data_cardmic_small")):
        img = render(size)
        fname = "cardmic_big.h" if size == 56 else "cardmic_small.h"
        with open(os.path.join(OUT, fname), "w") as f:
            f.write(to_header(img, name))
        if args.png_dir:
            os.makedirs(args.png_dir, exist_ok=True)
            img.save(os.path.join(args.png_dir, f"icon-{size}.png"))
            render(256, scale=4).save(os.path.join(args.png_dir, "icon-256.png"))
    print("icons written to", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
