#!/usr/bin/env python3
"""Generate the Cardmic launcher icons (56x56 and 40x40) as RGB565 C arrays.

The stock launcher draws each icon on a light-grey (#E6E6E6) rounded tile and
expects byte-swapped RGB565, which is what lcd-image-converter emitted for the
stock icons. The design follows the stock icon language: flat fills, heavy
black strokes and the stock pink / cyan / blue palette.

Usage: python3 tools/make_cardmic_icon.py [--png-dir DIR]
"""
import argparse
import os
from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "main", "apps", "app_cardmic", "assets")
TILE = (0xE6, 0xE6, 0xE6)
# Palette sampled from the stock launcher icons (ESP-NOW, Wi-Fi scan, REPL).
INK = (0x00, 0x00, 0x00)
PINK = (0xFF, 0x00, 0x62)
CYAN = (0x00, 0xCE, 0xFF)
BLUE = (0x00, 0x8D, 0xD5)
WHITE = (0xFF, 0xFF, 0xFF)


def render(size, scale=8):
    """A studio mic broadcasting both ways, in the stock icon language: flat
    fills, heavy black strokes, a black body with a coloured rim."""
    s = size * scale
    img = Image.new("RGB", (s, s), TILE)
    d = ImageDraw.Draw(img)
    u = lambda v: v * s  # unit -> pixels
    stroke = u(0.056)

    def line(p, q, col, w=stroke):
        d.line([u(p[0]), u(p[1]), u(q[0]), u(q[1])], fill=col, width=round(w))
        for x, y in (p, q):  # round caps
            d.ellipse([u(x) - w / 2, u(y) - w / 2, u(x) + w / 2, u(y) + w / 2], fill=col)

    def arc(cx, cy, r, a0, a1, col, w=stroke):
        box = [u(cx - r), u(cy - r), u(cx + r), u(cy + r)]
        d.arc(box, a0, a1, fill=col, width=round(w))
        import math
        for a in (a0, a1):  # round caps
            x = u(cx) + u(r) * math.cos(math.radians(a)) - (w / 2) * math.cos(math.radians(a))
            y = u(cy) + u(r) * math.sin(math.radians(a)) - (w / 2) * math.sin(math.radians(a))
            d.ellipse([x - w / 2, y - w / 2, x + w / 2, y + w / 2], fill=col)

    cx, cy = 0.5, 0.34  # capsule centre, also the centre of the waves
    # sound waves, left and right
    for r, col in ((0.285, CYAN), (0.395, BLUE)):
        arc(cx, cy, r, -34, 34, col)
        arc(cx, cy, r, 146, 214, col)
    # holder, stem, base
    arc(cx, 0.43, 0.165, 0, 180, INK)
    line((cx, 0.60), (cx, 0.80), INK)
    line((0.37, 0.82), (0.63, 0.82), INK)
    # capsule: black body, pink rim, white grille
    x0, x1, y0, y1 = 0.385, 0.615, 0.10, 0.575
    rad = (x1 - x0) / 2
    d.rounded_rectangle([u(x0), u(y0), u(x1), u(y1)], radius=u(rad), fill=PINK)
    rim = u(0.045)
    d.rounded_rectangle([u(x0) + rim, u(y0) + rim, u(x1) - rim, u(y1) - rim], radius=u(rad) - rim, fill=INK)
    for gy in (0.215, 0.285, 0.355):
        line((0.46, gy), (0.54, gy), WHITE, w=u(0.03))
    return img.resize((size, size), Image.LANCZOS)


def to_header(img, name):
    w, h = img.size
    words = []
    for r, g, b in img.getdata():
        c = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        words.append(((c & 0xFF) << 8) | (c >> 8))  # byte-swapped, as the stock icons
    lines = [", ".join(f"0x{v:04x}" for v in words[i:i + w]) for i in range(0, len(words), w)]
    body = ",\n    ".join(lines)
    return (f"// Generated by tools/make_cardmic_icon.py -- do not edit.\n"
            f"// {w}x{h}, byte-swapped RGB565, drawn on the stock #E6E6E6 icon tile.\n"
            f"#pragma once\n#include <stdint.h>\n\n"
            f"static const uint16_t {name}[{w * h}] = {{\n    {body}\n}};\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--png-dir")
    args = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)
    for size, name in ((56, "image_data_cardmic_big"), (40, "image_data_cardmic_small")):
        img = render(size)
        fname = "cardmic_big.h" if size == 56 else "cardmic_small.h"
        with open(os.path.join(OUT, fname), "w") as f:
            f.write(to_header(img, name))
        if args.png_dir:
            os.makedirs(args.png_dir, exist_ok=True)
            img.save(os.path.join(args.png_dir, f"icon-{size}.png"))
            render(256, scale=4).save(os.path.join(args.png_dir, "icon-256.png"))
    print("icons written to", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
